version: "3.7"
networks:
  kafka-network:
    driver: bridge
services:
  database:
    restart: "no"
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cashcog_db
    ports:
      - '5432:5432'
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - "kafka-network"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      - "kafka-network"
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cashcog-api:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - database
    ports:
      - "5000:5000"