version: "3.7"
services:
  database:
    restart: "no"
    container_name: database
    hostname: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cashcog_db
    ports:
      - '5432:5432'
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cashcog-api:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - database
    environment:
      - DB_HOST=database
      - WAIT_HOSTS=kafka:9092
      - BOOTSTRAP_SERVERS="kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
