# Generated by Django 3.0 on 2019-12-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uuid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_expenses', to='expenses.Expense')),
            ],
        ),
    ]
